version: '3'

services: 
    server:
        build:
            context: .
        volumes:
            - "./code:/code:rw"
        tty: true
        #devices:
            #- "/dev/ttyUSB0:/dev/ttyUSB0"
            #- "/dev/ttyACM0:/dev/ttyACM0"  
        ports:
            - "4000:4000"
