version: '3'

services: 
    server:
        build:
            context: .
        command: [/phx.sh]
        volumes:
            - "./ymn_link_web:/ymn_link_web:rw"
        tty: true
        devices:
            #- "/dev/ttyUSB0:/dev/ttyUSB0"
            - "/dev/ttyACM0:/dev/ttyACM0"  
        ports:
            - "4000:4000"
